SHELL := bash
.ONESHELL:
.SHELLFLAGS := -eu -o pipefail -c
.DELETE_ON_ERROR:
MAKEFLAGS += --warn-undefined-variables
MAKEFLAGS += --no-builtin-rules

build:
	@install -C -g root -o root -m 644 -T ./lightdm.conf /etc/lightdm/lightdm.conf
.PHONY: build
